export const pets = [
    {
        id: 1,
        name: '小猫',
        image: '/images/cat.jpg',
        character: '活泼',
        age: '2岁',
        breed: '中华田园猫',
        weight: '3kg',
        ownerTips: '喜欢互动，需要玩具和爬架',
        tags: ['友好', '爱玩', '适合室内'],
      },
      {
        id: 2,
        name: '小狗',
        image: '/images/dog.jpg',
        character: '温顺',
        age: '3岁',
        breed: '金毛',
        weight: '25kg',
        ownerTips: '需要定期遛狗，喜欢拥抱',
        tags: ['忠诚', '爱玩', '适合家庭'],
      },
      {
          id: 3,
          name: '鹦鹉',
          image: '/images/parrot.jpg',
          character: '活泼，聪明，喜欢与主人互动',
          age: '3岁',
          breed: '虎皮鹦鹉',
          weight: '100g',
          ownerTips: '需要提供丰富的玩具和社交互动',
          tags: ['鸟类', '聪明', '社交'],
          },
          {
          id: 4,
          name: '小兔',
          image: '/images/rabbit.jpeg',
          character: '安静',
          age: '1岁',
          breed: '荷兰兔',
          weight: '1.5kg',
          ownerTips: '喜欢吃胡萝卜和草，适合室内饲养',
          tags: ['安静', '爱吃', '适合家庭'],
        },
          {
          id: 5,
          name: '仓鼠',
          image: '/images/hamster.jpg',
          character: '活泼、好动，喜欢夜间活动',
          age: '2岁',
          breed: '叙利亚仓鼠',
          weight: '150g',
          ownerTips: '需要适当的活动空间和玩具',
          tags: ['小型动物', '夜行性', '爱跑'],
          },
          {
          id: 6,
          name: '金鱼',
          image: '/images/golden_fish.jpg',
          character: '温和、优雅',
          age: '5岁',
          breed: '红色金鱼',
          weight: '50g',
          ownerTips: '保持水质清洁，提供均衡饮食',
          tags: ['水生', '优雅', '低维护'],
          },
          {
          id: 7,
          name: '龙猫',
          image: '/images/chinchilla.jpeg',
          character: '活泼、好奇，喜欢在夜间活动',
          age: '3岁',
          breed: '长毛龙猫',
          weight: '500g',
          ownerTips: '提供足够的空间和跑轮',
          tags: ['夜行性', '活泼', '爱跳'],
          },
          {
          id: 8,
          name: '乌龟',
          image: '/images/turtle.jpeg',
          character: '温和、耐心',
          age: '10岁',
          breed: '巴西龟',
          weight: '1kg',
          ownerTips: '提供适当水域和晒太阳区域',
          tags: ['爬行动物', '低维护', '耐心'],
          },
          {
          id: 9,
          name: '刺猬',
          image: '/images/hedgehog.jpeg',
          character: '独立、好奇，夜间活动',
          age: '4岁',
          breed: '非洲刺猬',
          weight: '400g',
          ownerTips: '提供适合的环境和充足的食物',
          tags: ['小型动物', '夜行性', '独立'],
          },
          {
          id: 10,
          name: '松鼠',
          image: '/images/squirrel.webp',
          character: '活泼、好奇',
          age: '3岁',
          breed: '红松鼠',
          weight: '300g',
          ownerTips: '提供充足的食物和活动空间',
          tags: ['小型动物', '好奇', '活泼'],
          },
          {
          id: 11,
          name: '八哥鸟',
          image: '/images/myna.jpg',
          character: '爱模仿、活泼',
          age: '2岁',
          breed: '八哥',
          weight: '150g',
          ownerTips: '喜欢与人互动，提供丰富的活动空间',
          tags: ['鸟类', '聪明', '社交'],
          },
          {
          id: 12,
          name: '蜥蜴',
          image: '/images/lizard.jpg',
          character: '冷静、独立',
          age: '5年',
          breed: '变色龙',
          weight: '200g',
          ownerTips: '提供适当温度和湿度',
          tags: ['爬行动物', '低维护', '独立'],
          },
          {
          id: 13,
          name: '锦鲤',
          image: '/images/koi_fish.jpg',
          character: '温和、优雅',
          age: '4年',
          breed: '锦鲤',
          weight: '2kg',
          ownerTips: '保持水质清洁，提供充足的空间',
          tags: ['水生', '优雅', '长寿'],
          },
          {
          id: 14,
          name: '变色龙',
          image: '/images/chameleon.jpeg',
          character: '冷静、独立',
          age: '5年',
          breed: '变色龙',
          weight: '200g',
          ownerTips: '提供适当温度和湿度',
          tags: ['爬行动物', '低维护', '独立'],
          },                       
          {
          id: 15,
          name: '荷兰猪',
          image: '/images/guinea_pig.webp',
          character: '温顺、亲人',
          age: '2岁',
          breed: '荷兰猪',
          weight: '1kg',
          ownerTips: '提供适当的食物和活动空间',
          tags: ['小型动物', '温顺', '亲人'],
          },
          {
          id: 16,
          name: '蜜袋鼯',
          image: '/images/sugar_glider.jpg',
          character: '活泼、好奇',
          age: '3岁',
          breed: '蜜袋鼯',
          weight: '250g',
          ownerTips: '提供丰富的食物和社交互动',
          tags: ['小型动物', '活泼', '社交'],
          },
          {
          id: 17,
          name: '蝴蝶犬',
          image: '/images/papillon.jpg',
          character: '机警、聪明',
          age: '4岁',
          breed: '蝴蝶犬',
          weight: '3kg',
          ownerTips: '需要定期梳毛，适合家庭饲养',
          tags: ['犬类', '机警', '聪明'],
          },
          {
          id: 18,
          name: '松狮',
          image: '/images/chow_chow.jpg',
          character: '忠诚、温和',
          age: '5岁',
          breed: '松狮犬',
          weight: '20kg',
          ownerTips: '需要适当的运动和梳理',
          tags: ['犬类', '忠诚', '温和'],
          },
          {
          id: 19,
          name: '锦蛇',
          image: '/images/corn_snake.jpg.jpg',
          character: '冷静、低调',
          age: '2年',
          breed: '锦蛇',
          weight: '1kg',
          ownerTips: '保持环境温暖湿润，避免打扰',
          tags: ['爬行动物', '低调', '冷静'],
          },
          {
          id: 20,
          name: '仓鸽',
          image: '/images/homing_pigeon.jpeg',
          character: '温顺、聪明',
          age: '3年',
          breed: '普通鸽',
          weight: '300g',
          ownerTips: '提供足够的飞行空间和饮水',
          tags: ['鸟类', '温顺', '聪明'],
          },
]