export const pets = [
    {
        id: 1,
        name: '小猫',
        image: 'https://img.alicdn.com/bao/uploaded/i1/2209835391252/O1CN013IXaMa1L7SXe8qSkO_!!2209835391252.jpg',
        character: '活泼',
        age: '2岁',
        breed: '中华田园猫',
        weight: '3kg',
        ownerTips: '喜欢互动，需要玩具和爬架',
        tags: ['友好', '爱玩', '适合室内'],
      },
      {
        id: 2,
        name: '小狗',
        image: 'https://th.bing.com/th/id/R.264e0e2adbb5ebeed7d774a1a6989e6e?rik=7SlM7BsVhdqxhA&riu=http%3a%2f%2fpic.bizhi360.com%2fbpic%2f54%2f354.jpg&ehk=0x7R%2f%2bI33ol1eY5%2fZN36ohssKifRzHLxJ4AOvtRaON4%3d&risl=&pid=ImgRaw&r=0',
        character: '温顺',
        age: '3岁',
        breed: '金毛',
        weight: '25kg',
        ownerTips: '需要定期遛狗，喜欢拥抱',
        tags: ['忠诚', '爱玩', '适合家庭'],
      },
      {
          id: 3,
          name: '鹦鹉',
          image: 'https://pic.52112.com/180209/180209_86/owf0vzSMGH.jpg',
          character: '活泼，聪明，喜欢与主人互动',
          age: '3岁',
          breed: '虎皮鹦鹉',
          weight: '100g',
          ownerTips: '需要提供丰富的玩具和社交互动',
          tags: ['鸟类', '聪明', '社交'],
          },
          {
          id: 4,
          name: '小兔',
          image: 'https://th.bing.com/th/id/OIP.WSLL-7Sd1_m8PA0WJATOSAHaE8?rs=1&pid=ImgDetMain',
          character: '安静',
          age: '1岁',
          breed: '荷兰兔',
          weight: '1.5kg',
          ownerTips: '喜欢吃胡萝卜和草，适合室内饲养',
          tags: ['安静', '爱吃', '适合家庭'],
        },
          {
          id: 5,
          name: '仓鼠',
          image: 'https://pic4.zhimg.com/v2-d0d586b47421d49d3e5fbae16ab4e247_r.jpg',
          character: '活泼、好动，喜欢夜间活动',
          age: '2岁',
          breed: '叙利亚仓鼠',
          weight: '150g',
          ownerTips: '需要适当的活动空间和玩具',
          tags: ['小型动物', '夜行性', '爱跑'],
          },
          {
          id: 6,
          name: '金鱼',
          image: 'https://pic.nximg.cn/file/20230817/33760392_143224583126_2.jpg',
          character: '温和、优雅',
          age: '5岁',
          breed: '红色金鱼',
          weight: '50g',
          ownerTips: '保持水质清洁，提供均衡饮食',
          tags: ['水生', '优雅', '低维护'],
          },
          {
          id: 7,
          name: '龙猫',
          image: 'https://th.bing.com/th/id/OIP.YatIXfoUnJe-KCLfRa-kuwHaGj?rs=1&pid=ImgDetMain',
          character: '活泼、好奇，喜欢在夜间活动',
          age: '3岁',
          breed: '长毛龙猫',
          weight: '500g',
          ownerTips: '提供足够的空间和跑轮',
          tags: ['夜行性', '活泼', '爱跳'],
          },
          {
          id: 8,
          name: '乌龟',
          image: 'https://img95.699pic.com/photo/60080/3590.jpg_wh860.jpg',
          character: '温和、耐心',
          age: '10岁',
          breed: '巴西龟',
          weight: '1kg',
          ownerTips: '提供适当水域和晒太阳区域',
          tags: ['爬行动物', '低维护', '耐心'],
          },
          {
          id: 9,
          name: '刺猬',
          image: 'https://th.bing.com/th/id/R.1984763d8fd10974aeffe0de38fca1a2?rik=KZrCpBPiXq7UoQ&riu=http%3a%2f%2fpic.baike.soso.com%2fugc%2fbaikepic2%2f23219%2f20170218212406-832416629.jpg%2f0&ehk=LN4NF0AL1l%2fj%2fN%2byr3HE65%2boIw6q0omfWjxDM%2bgSWVE%3d&risl=&pid=ImgRaw&r=0',
          character: '独立、好奇，夜间活动',
          age: '4岁',
          breed: '非洲刺猬',
          weight: '400g',
          ownerTips: '提供适合的环境和充足的食物',
          tags: ['小型动物', '夜行性', '独立'],
          },
          {
          id: 10,
          name: '松鼠',
          image: 'https://th.bing.com/th/id/R.60e5000280fa18f34c24a7d89902b58c?rik=58I%2fsuGZ0ldpPw&riu=http%3a%2f%2fpic21.nipic.com%2f20120529%2f5252423_184207506000_2.jpg&ehk=Ko83GavycmBfb7iSfN1AT9ml8UAjtPzhjPNx6%2bzqL6w%3d&risl=&pid=ImgRaw&r=0',
          character: '活泼、好奇',
          age: '3岁',
          breed: '红松鼠',
          weight: '300g',
          ownerTips: '提供充足的食物和活动空间',
          tags: ['小型动物', '好奇', '活泼'],
          },
          {
          id: 11,
          name: '八哥鸟',
          image: 'https://cdnappimg.dongniaodi.com/tukuimgs/2/20201104144850_473521.jpg',
          character: '爱模仿、活泼',
          age: '2岁',
          breed: '八哥',
          weight: '150g',
          ownerTips: '喜欢与人互动，提供丰富的活动空间',
          tags: ['鸟类', '聪明', '社交'],
          },
          {
          id: 12,
          name: '蜥蜴',
          image: 'https://img95.699pic.com/photo/32119/2847.jpg_wh860.jpg',
          character: '冷静、独立',
          age: '5年',
          breed: '变色龙',
          weight: '200g',
          ownerTips: '提供适当温度和湿度',
          tags: ['爬行动物', '低维护', '独立'],
          },
          {
          id: 13,
          name: '锦鲤',
          image: 'https://photo-static-api.fotomore.com/creative/vcg/veer/612/veer-158536057.jpg',
          character: '温和、优雅',
          age: '4年',
          breed: '锦鲤',
          weight: '2kg',
          ownerTips: '保持水质清洁，提供充足的空间',
          tags: ['水生', '优雅', '长寿'],
          },
          {
          id: 14,
          name: '变色龙',
          image: 'https://th.bing.com/th/id/R.016d33cbf24c304dd2b3b55b2c8f283d?rik=BHpIWNOGXQskDQ&riu=http%3a%2f%2fimg0.dili360.com%2fga%2fM02%2f00%2fFF%2fwKgBy1Q2gnCAGSTlAAJldVmRnMU559.jpg%40!rw17&ehk=J94fweCbspD7%2bMoLGnd%2fGnpnQoQgpRTyzMVlvQ6Pu5Q%3d&risl=&pid=ImgRaw&r=0',
          character: '冷静、独立',
          age: '5年',
          breed: '变色龙',
          weight: '200g',
          ownerTips: '提供适当温度和湿度',
          tags: ['爬行动物', '低维护', '独立'],
          },                       
          {
          id: 15,
          name: '荷兰猪',
          image: 'https://p5.itc.cn/q_70/images03/20230101/79f18bd194a44efaa2e86066183186f5.png',
          character: '温顺、亲人',
          age: '2岁',
          breed: '荷兰猪',
          weight: '1kg',
          ownerTips: '提供适当的食物和活动空间',
          tags: ['小型动物', '温顺', '亲人'],
          },
          {
          id: 16,
          name: '蜜袋鼯',
          image: 'https://www.newton.com.tw/img/1/ff3/cGcq5iMmNWZlBzM3YGN3UWNilzM3Y2NxIjN3QzLtVGdp9yYpB3LltWahJ2Lt92YuUHZpFmYuMmczdWbp9yL6MHc0RHa.jpg',
          character: '活泼、好奇',
          age: '3岁',
          breed: '蜜袋鼯',
          weight: '250g',
          ownerTips: '提供丰富的食物和社交互动',
          tags: ['小型动物', '活泼', '社交'],
          },
          {
          id: 17,
          name: '蝴蝶犬',
          image: 'https://pic4.zhimg.com/v2-8ac22138dfc5aa39eb67ba1c97db63ef_r.jpg',
          character: '机警、聪明',
          age: '4岁',
          breed: '蝴蝶犬',
          weight: '3kg',
          ownerTips: '需要定期梳毛，适合家庭饲养',
          tags: ['犬类', '机警', '聪明'],
          },
          {
          id: 18,
          name: '松狮',
          image: 'https://pic.nximg.cn/file/20170711/25232793_123724124000_2.jpg',
          character: '忠诚、温和',
          age: '5岁',
          breed: '松狮犬',
          weight: '20kg',
          ownerTips: '需要适当的运动和梳理',
          tags: ['犬类', '忠诚', '温和'],
          },
          {
          id: 19,
          name: '锦蛇',
          image: 'https://so1.360tres.com/t01c052d49822e6b7b3.jpg',
          character: '冷静、低调',
          age: '2年',
          breed: '锦蛇',
          weight: '1kg',
          ownerTips: '保持环境温暖湿润，避免打扰',
          tags: ['爬行动物', '低调', '冷静'],
          },
          {
          id: 20,
          name: '仓鸽',
          image: 'https://th.bing.com/th/id/OIP.XYRvsF8pFsG6X5GQepojowAAAA?rs=1&pid=ImgDetMain',
          character: '温顺、聪明',
          age: '3年',
          breed: '普通鸽',
          weight: '300g',
          ownerTips: '提供足够的飞行空间和饮水',
          tags: ['鸟类', '温顺', '聪明'],
          },
]